name: 自动部署
 
on:
  push:
    branches:
      - main  # default branch
jobs:
  build: 
    runs-on: ubuntu-latest 
         
    steps:
    # check it to your workflow can access it
    # from: https://github.com/actions/checkout
    - name: Checkout Repository master branch
      uses: actions/checkout@master 
      
    # from: https://github.com/actions/setup-node  
  
    - name: Gitee设置
      env:
        GH_ACTION_DEPLOY_KEY: ${{ secrets.GITEE_KEY }}
      run: |
        # set up private key for deploy
        mkdir -p ~/.ssh/
        echo "$GH_ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa 
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan gitee.com >> ~/.ssh/known_hosts
        git config --global user.name 'dlyt'  
        git config --global user.email '472548557@qq.com' 
    - name: push到Gitee
      run: |
        cd pic
        ls
        git init
        git config --global --list
        git add .
        git commit -m "CI built at `date +"%Y-%m-%d %H:%M:%S"`"
        git branch -M master
        git remote add origin git@gitee.com:dlytang/cdn.git
        git push -u origin master -f
        
    - name: Build Gitee Pages
      uses: yanglbme/gitee-pages-action@main
      with:
        # 注意替换为你的 Gitee 用户名
        gitee-username: dlytang
        # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
        gitee-password: ${{ secrets.GITEE_PASSWORD }}
        # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
        gitee-repo: dlytang/cdn
        # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
        branch: master
